create table if not exists public.audit_logs (
  id bigint generated by default as identity primary key,
  entity_type text not null,
  entity_id text not null,
  action text not null,
  actor_user_id text,
  actor_email text,
  actor_role text,
  details jsonb not null default '{}'::jsonb,
  created_at timestamptz not null default now()
);

create index if not exists idx_audit_logs_created on public.audit_logs (created_at desc);

alter table public.audit_logs enable row level security;

drop policy if exists "service role manages audit logs" on public.audit_logs;
create policy "service role manages audit logs"
on public.audit_logs
for all
using (auth.role() = 'service_role')
with check (auth.role() = 'service_role');
