create table if not exists public.member_profiles (
  user_id uuid primary key references auth.users(id) on delete cascade,
  display_name text,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create table if not exists public.article_bookmarks (
  user_id uuid not null references auth.users(id) on delete cascade,
  article_key text not null,
  created_at timestamptz not null default now(),
  primary key (user_id, article_key)
);

create table if not exists public.article_comments (
  id bigint generated by default as identity primary key,
  article_key text not null,
  user_id uuid not null references auth.users(id) on delete cascade,
  author_handle text not null,
  body text not null check (char_length(body) between 2 and 2000),
  status text not null default 'approved' check (status in ('pending','approved','hidden')),
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create index if not exists idx_article_comments_key on public.article_comments (article_key, created_at desc);
create index if not exists idx_article_comments_user on public.article_comments (user_id, created_at desc);

alter table public.member_profiles enable row level security;
alter table public.article_bookmarks enable row level security;
alter table public.article_comments enable row level security;

drop policy if exists "members can read own profile" on public.member_profiles;
create policy "members can read own profile"
on public.member_profiles
for select
to authenticated
using (auth.uid() = user_id);

drop policy if exists "members can insert own profile" on public.member_profiles;
create policy "members can insert own profile"
on public.member_profiles
for insert
to authenticated
with check (auth.uid() = user_id);

drop policy if exists "members can update own profile" on public.member_profiles;
create policy "members can update own profile"
on public.member_profiles
for update
to authenticated
using (auth.uid() = user_id)
with check (auth.uid() = user_id);

drop policy if exists "members can read own bookmarks" on public.article_bookmarks;
create policy "members can read own bookmarks"
on public.article_bookmarks
for select
to authenticated
using (auth.uid() = user_id);

drop policy if exists "members can insert own bookmarks" on public.article_bookmarks;
create policy "members can insert own bookmarks"
on public.article_bookmarks
for insert
to authenticated
with check (auth.uid() = user_id);

drop policy if exists "members can delete own bookmarks" on public.article_bookmarks;
create policy "members can delete own bookmarks"
on public.article_bookmarks
for delete
to authenticated
using (auth.uid() = user_id);

drop policy if exists "public can read approved comments" on public.article_comments;
create policy "public can read approved comments"
on public.article_comments
for select
using (status = 'approved' or auth.uid() = user_id);

drop policy if exists "members can insert own comments" on public.article_comments;
create policy "members can insert own comments"
on public.article_comments
for insert
to authenticated
with check (auth.uid() = user_id);

drop policy if exists "members can update own comments" on public.article_comments;
create policy "members can update own comments"
on public.article_comments
for update
to authenticated
using (auth.uid() = user_id)
with check (auth.uid() = user_id);

drop policy if exists "members can delete own comments" on public.article_comments;
create policy "members can delete own comments"
on public.article_comments
for delete
to authenticated
using (auth.uid() = user_id);
