create extension if not exists pgcrypto;

create table if not exists public.articles (
  id text primary key,
  slug text not null unique,
  title text not null,
  subtitle text,
  summary text,
  full_content text,
  type text not null default 'article',
  status text not null default 'draft',
  featured boolean not null default false,
  pinned boolean not null default false,
  editorial_weight integer not null default 0,
  published_at timestamptz,
  image_url text,
  image_alt text,
  creators jsonb not null default '[]'::jsonb,
  categories jsonb not null default '[]'::jsonb,
  category_slugs jsonb not null default '[]'::jsonb,
  tags jsonb not null default '[]'::jsonb,
  tag_slugs jsonb not null default '[]'::jsonb,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

alter table if exists public.articles add column if not exists full_content text;
alter table if exists public.articles add column if not exists created_at timestamptz not null default now();
alter table if exists public.articles add column if not exists updated_at timestamptz not null default now();

do $$
begin
  if not exists (
    select 1
    from pg_constraint
    where conname = 'articles_status_check'
      and conrelid = 'public.articles'::regclass
  ) then
    alter table public.articles
      add constraint articles_status_check
      check (status in ('draft','in_review','approved','published'));
  end if;
end
$$;

create table if not exists public.forum_posts (
  id bigint generated by default as identity primary key,
  title text not null,
  handle text not null,
  votes integer not null default 0,
  article_key text,
  is_hidden boolean not null default false,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

alter table if exists public.forum_posts add column if not exists is_hidden boolean not null default false;
alter table if exists public.forum_posts add column if not exists created_at timestamptz not null default now();
alter table if exists public.forum_posts add column if not exists updated_at timestamptz not null default now();

create table if not exists public.publisher_profiles (
  user_id uuid primary key references auth.users(id) on delete cascade,
  email text not null unique,
  role text not null check (role in ('writer','editor','publisher','admin')),
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create table if not exists public.audit_logs (
  id bigint generated by default as identity primary key,
  entity_type text not null,
  entity_id text not null,
  action text not null,
  actor_user_id text,
  actor_email text,
  actor_role text,
  details jsonb not null default '{}'::jsonb,
  created_at timestamptz not null default now()
);

create index if not exists idx_articles_publish on public.articles (status, published_at desc);
create index if not exists idx_articles_order on public.articles (pinned desc, editorial_weight desc, published_at desc);
create index if not exists idx_forum_posts_order on public.forum_posts (is_hidden, votes desc, id desc);
create index if not exists idx_audit_logs_created on public.audit_logs (created_at desc);

alter table public.articles enable row level security;
alter table public.forum_posts enable row level security;
alter table public.publisher_profiles enable row level security;
alter table public.audit_logs enable row level security;

drop policy if exists "public can read published articles" on public.articles;
create policy "public can read published articles"
on public.articles
for select
using (status = 'published' and published_at <= now());

drop policy if exists "public can read visible forum posts" on public.forum_posts;
create policy "public can read visible forum posts"
on public.forum_posts
for select
using (is_hidden = false);

drop policy if exists "authenticated can read own profile" on public.publisher_profiles;
create policy "authenticated can read own profile"
on public.publisher_profiles
for select
to authenticated
using (auth.uid() = user_id);

drop policy if exists "service role manages articles" on public.articles;
create policy "service role manages articles"
on public.articles
for all
using (auth.role() = 'service_role')
with check (auth.role() = 'service_role');

drop policy if exists "service role manages forum posts" on public.forum_posts;
create policy "service role manages forum posts"
on public.forum_posts
for all
using (auth.role() = 'service_role')
with check (auth.role() = 'service_role');

drop policy if exists "service role manages publisher profiles" on public.publisher_profiles;
create policy "service role manages publisher_profiles"
on public.publisher_profiles
for all
using (auth.role() = 'service_role')
with check (auth.role() = 'service_role');

drop policy if exists "service role manages audit logs" on public.audit_logs;
create policy "service role manages audit logs"
on public.audit_logs
for all
using (auth.role() = 'service_role')
with check (auth.role() = 'service_role');
