create extension if not exists pgcrypto;

create table if not exists public.articles (
  id text primary key,
  slug text not null unique,
  title text not null,
  subtitle text,
  summary text,
  full_content text,
  type text not null default 'article',
  status text not null default 'draft',
  featured boolean not null default false,
  pinned boolean not null default false,
  editorial_weight integer not null default 0,
  published_at timestamptz,
  image_url text,
  image_alt text,
  creators jsonb not null default '[]'::jsonb,
  categories jsonb not null default '[]'::jsonb,
  category_slugs jsonb not null default '[]'::jsonb,
  tags jsonb not null default '[]'::jsonb,
  tag_slugs jsonb not null default '[]'::jsonb,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create table if not exists public.forum_posts (
  id bigint generated by default as identity primary key,
  title text not null,
  handle text not null,
  votes integer not null default 0,
  article_key text,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create index if not exists idx_articles_publish on public.articles (status, published_at desc);
create index if not exists idx_articles_order on public.articles (pinned desc, editorial_weight desc, published_at desc);
create index if not exists idx_forum_posts_order on public.forum_posts (votes desc, id desc);

alter table public.articles enable row level security;
alter table public.forum_posts enable row level security;

drop policy if exists "public can read published articles" on public.articles;
create policy "public can read published articles"
on public.articles
for select
using (status = 'published' and published_at <= now());

drop policy if exists "public can read forum posts" on public.forum_posts;
create policy "public can read forum posts"
on public.forum_posts
for select
using (true);

drop policy if exists "service role manages articles" on public.articles;
create policy "service role manages articles"
on public.articles
for all
using (auth.role() = 'service_role')
with check (auth.role() = 'service_role');

drop policy if exists "service role manages forum posts" on public.forum_posts;
create policy "service role manages forum posts"
on public.forum_posts
for all
using (auth.role() = 'service_role')
with check (auth.role() = 'service_role');
